In [30]:
import numpy as np


### 🎯 **Objective:**

You are working with student marks data and need to prepare and organize it using NumPy arrays.Your goal is to create, modify, and analyze the data efficiently without using any external libraries.

### 🧠 **Project Description:**

A school has recorded the marks of several students in different subjects.You are required to design a NumPy-based solution to store, manage, and process this data.Your tasks involve creating arrays, changing their shapes, combining data, performing modifications, and analyzing patterns — all using NumPy.

### 📋 **Project Tasks:**

1.  **Data Creation:**Create suitable arrays to represent students, subjects, and their marks.
    
2.  **Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.
    
3.  **Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.
    
4.  **Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.
    
5.  **Data Modification:**Apply operations to update marks, remove data, or identify unique information.
    
6.  **Data Type Handling:**Demonstrate how the same data can exist in different data types and how changes affect results.
    
7.  **Copy and View Behavior:**Show the difference between creating a full copy of an array and creating a view of the same data.

1.  **Data Creation:**Create suitable arrays to represent students, subjects, and their marks.


In [31]:
# Creation of 2D array Assuming students and subjects as marks
# Assume: 5 students (rows), 4 subjects (columns)

marks = np.array([
    [78, 82, 69, 90],
    [88, 75, 92, 85],
    [80, 70, 88, 78],
    [65, 60, 75, 70],
    [90, 85, 95, 88]
])
print("CREATION OF 2D ARRAY\n",marks)

CREATION OF 2D ARRAY
 [[78 82 69 90]
 [88 75 92 85]
 [80 70 88 78]
 [65 60 75 70]
 [90 85 95 88]]


2.  **Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.

In [32]:
#Displaying the array properties

#Shape of the array
print("SHAPE OF THE ARRY:",marks.shape)

#Dimensions of array
print("DIMENSIONS OF THE ARRY:",marks.ndim)

#Size of the array
print("SIZE OF THE ARRAY",marks.size)

#datatype of array elements
print("DATATYPE OF ARRAY ELEMENTS",marks.dtype)

SHAPE OF THE ARRY: (5, 4)
DIMENSIONS OF THE ARRY: 2
SIZE OF THE ARRAY 20
DATATYPE OF ARRAY ELEMENTS int64


3.**Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.

In [33]:
# TRANSFORMING THE ARRAY DATA
# Transpose (swap rows & columns)
transposed = marks.T
# Reshape into new 2D form (2 rows, 10 columns)
reshaped = marks.reshape(2, 10)
# Flatten back to 2D (1 row, all values)
flattened_2d = marks.reshape(1, -1)

print("Transposed (Subjects as Rows):\n", transposed)
print("Reshaped (2x10):\n", reshaped)
print("Flattened (1xN 2D Form):\n", flattened_2d)

Transposed (Subjects as Rows):
 [[78 88 80 65 90]
 [82 75 70 60 85]
 [69 92 88 75 95]
 [90 85 78 70 88]]
Reshaped (2x10):
 [[78 82 69 90 88 75 92 85 80 70]
 [88 78 65 60 75 70 90 85 95 88]]
Flattened (1xN 2D Form):
 [[78 82 69 90 88 75 92 85 80 70 88 78 65 60 75 70 90 85 95 88]]


4.  **Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.

In [34]:
# DATA COMBINATION
# Add a new student (new row)
new_student = np.array([[85, 80, 75, 88]])
marks = np.vstack((marks, new_student))

# Add a new subject (new column)
new_subject = np.array([[70], [68], [72], [60], [90], [80]])
marks = np.hstack((marks, new_subject))

print("After Adding New Student and Subject\n", marks)

After Adding New Student and Subject
 [[78 82 69 90 70]
 [88 75 92 85 68]
 [80 70 88 78 72]
 [65 60 75 70 60]
 [90 85 95 88 90]
 [85 80 75 88 80]]


5.  **Data Modification:**Apply operations to update marks, remove data, or identify unique information.

In [35]:
# Modifying the data like update marks,deleting the students and finding unique values
# Remove one student (4th row)
marks = np.delete(marks, 3, axis=0)
# Unique marks
unique_vals = np.unique(marks)

print("After Modifications\n", marks)
print("Unique Marks\n", unique_vals)

After Modifications
 [[78 82 69 90 70]
 [88 75 92 85 68]
 [80 70 88 78 72]
 [90 85 95 88 90]
 [85 80 75 88 80]]
Unique Marks
 [68 69 70 72 75 78 80 82 85 88 90 92 95]


6.  **Data Type Handling:**Demonstrate how the same data can exist in different data types and how changes affect results.

In [36]:
# Changing The datatype of array elements such as float complex str
#Converting into float datatype
marks_float = marks.astype(float)

#converting into complex datatype
marks_complex = marks.astype(complex)

#converting into str data type
marks_str = marks.astype(str)

print("Float Data Type\n", marks_float)
print("Complex Data Type\n", marks_complex)
print("String Data Type\n", marks_str)



Float Data Type
 [[78. 82. 69. 90. 70.]
 [88. 75. 92. 85. 68.]
 [80. 70. 88. 78. 72.]
 [90. 85. 95. 88. 90.]
 [85. 80. 75. 88. 80.]]
Complex Data Type
 [[78.+0.j 82.+0.j 69.+0.j 90.+0.j 70.+0.j]
 [88.+0.j 75.+0.j 92.+0.j 85.+0.j 68.+0.j]
 [80.+0.j 70.+0.j 88.+0.j 78.+0.j 72.+0.j]
 [90.+0.j 85.+0.j 95.+0.j 88.+0.j 90.+0.j]
 [85.+0.j 80.+0.j 75.+0.j 88.+0.j 80.+0.j]]
String Data Type
 [['78' '82' '69' '90' '70']
 ['88' '75' '92' '85' '68']
 ['80' '70' '88' '78' '72']
 ['90' '85' '95' '88' '90']
 ['85' '80' '75' '88' '80']]


7.  **Copy and View Behavior:**Show the difference between creating a full copy of an array and creating a view of the same data.


In [37]:
# Showing the diffrence between creating a array using copy and view

marks_copy = marks.copy()
marks_view = marks.view()

# Modify original
marks[0, 0] = 999

print("Original Marks\n", marks)
print("Copy (NOT CHANGED)\n", marks_copy)
print("View (CHANGED):\n", marks_view)

Original Marks
 [[999  82  69  90  70]
 [ 88  75  92  85  68]
 [ 80  70  88  78  72]
 [ 90  85  95  88  90]
 [ 85  80  75  88  80]]
Copy (NOT CHANGED)
 [[78 82 69 90 70]
 [88 75 92 85 68]
 [80 70 88 78 72]
 [90 85 95 88 90]
 [85 80 75 88 80]]
View (CHANGED):
 [[999  82  69  90  70]
 [ 88  75  92  85  68]
 [ 80  70  88  78  72]
 [ 90  85  95  88  90]
 [ 85  80  75  88  80]]
